import type {
  PackageServiceConfig,
  PackageServiceKey,
} from "./packageTypes";

export const packageServiceOrder: PackageServiceKey[] = [
  "website",
  "branding",
  "social-media",
  "digital-marketing",
  "advertising",
  "content-production",
  "consultation",
];

export const packageCatalog: Record<
  PackageServiceKey,
  PackageServiceConfig
> = {
  website: {
    key: "website",
    label: "Website Solutions",
    route: "/tanya-mahreen/paket/website",
    eyebrow: "Website Solutions",
    title: "Konfigurasi Paket Anda",
    description:
      "Tailor-made digital experiences meticulously crafted to elevate your brand's digital presence with obsidian precision and gilt excellence.",
    tiers: [
      {
        id: "professional",
        tier: "Tier 01",
        name: "Better Package",
        price: 1_500_000,
        features: [
          "Company Profile (maks. 5 halaman)",
          "Logo Design",
          "Integrasi WhatsApp",
          "Google Business Profile Setup",
          "Basic SEO",
          "Domain & Hosting Setup",
          "Support 30 hari",
        ],
      },
      {
        id: "business",
        tier: "Tier 02",
        name: "Good Package",
        price: 2_500_000,
        features: [
          "Company Profile Website",
          "Landing Page",
          "Logo Design",
          "Basic SEO",
          "Google Analytics & Search Console",
          "Integrasi WhatsApp",
          "Form Lead",
          "Pelatihan Admin",
          "Support 60 hari",
          "Free Banner & Speed Optimization",
        ],
        recommended: true,
      },
      {
        id: "enterprise",
        tier: "Tier 03",
        name: "Best Package",
        price: 4_500_000,
        features: [
          "Website Development",
          "Dashboard Admin",
          "Database Integration",
          "Multi User Support",
          "Landing Page",
          "Logo Design",
          "SEO Basic",
          "Performance Optimization",
          "UI/UX Design",
          "Dokumentasi Sistem",
          "Support 90 hari",
        ],
      },
    ],
    comparisonRows: [
      {
        label: "Mobile Responsiveness",
        professional: true,
        business: true,
        enterprise: true,
      },
      {
        label: "Visual Design Style",
        professional: "Standard",
        business: "Custom Luxury",
        enterprise: "Bespoke Artisan",
      },
      {
        label: "Content Writing",
        professional: false,
        business: "Hingga 3 halaman",
        enterprise: true,
      },
      {
        label: "Dynamic Components",
        professional: false,
        business: true,
        enterprise: true,
      },
      {
        label: "Custom Code Access",
        professional: false,
        business: false,
        enterprise: true,
      },
    ],
    addOns: [
      {
        id: "website-maintenance",
        title: "Monthly Maintenance",
        description: "Pembaruan, keamanan, dan laporan rutin bulanan.",
        priceLabel: "+Rp250k/bulan",
        priceValue: 250_000,
      },
      {
        id: "website-domain",
        title: "Domain & Hosting (1 Tahun)",
        description: "Domain .com dan server hosting premium selama satu tahun.",
        priceLabel: "+Rp500k",
        priceValue: 500_000,
      },
      {
        id: "website-copywriting",
        title: "Premium Content Writing",
        description: "Copywriting berorientasi penjualan untuk seluruh bagian website.",
        priceLabel: "+Rp750k",
        priceValue: 750_000,
      },
      {
        id: "website-ecommerce",
        title: "Basic E-commerce Module",
        description: "Pengaturan hingga 10 produk beserta alur checkout.",
        priceLabel: "+Rp400k",
        priceValue: 400_000,
      },
    ],
  },

  branding: {
    key: "branding",
    label: "Branding & Design",
    route: "/tanya-mahreen/paket/branding",
    eyebrow: "Branding & Design",
    title: "Konfigurasi Paket Anda",
    description:
      "Bangun identitas visual yang konsisten, bernilai, dan mudah dikenali melalui paket branding yang dapat disesuaikan dengan tahap pertumbuhan bisnis Anda.",
    tiers: [
      {
        id: "professional",
        tier: "Tier 01",
        name: "Better Package",
        price: 499_000,
        features: [
          "Logo Design (2 alternatif konsep)",
          "Revisi maksimal 2 kali",
          "Color Palette",
          "File PNG, JPG, PDF",
          "Logo Mockup",
          "Gratis konsultasi 30 menit",
          "Social Media Ready Files",
        ],
      },
      {
        id: "business",
        tier: "Tier 02",
        name: "Good Package",
        price: 1_499_000,
        features: [
          "Logo Design",
          "Brand Identity",
          "Brand Guideline",
          "Typography & Color Palette",
          "Social Media Identity",
          "Stationery Mockup",
          "5 Template Feed Instagram",
          "File lengkap PNG, JPG, PDF, SVG",
          "Konsultasi 1 jam + support 7 hari",
        ],
        recommended: true,
      },
      {
        id: "enterprise",
        tier: "Tier 03",
        name: "Best Package",
        price: 1_999_000,
        features: [
          "Logo Design & Brand Identity",
          "Brand Guideline",
          "Company Profile Design",
          "Presentation Design",
          "Packaging Design",
          "Marketing Materials (2 pilihan)",
          "Social Media Identity",
          "Stationery Design",
          "Prioritas pengerjaan & support 14 hari",
        ],
      },
    ],
    comparisonRows: [
      {
        label: "Alternatif Konsep Logo",
        professional: "2 konsep",
        business: "3 konsep",
        enterprise: "4 konsep",
      },
      {
        label: "Jumlah Revisi",
        professional: "2 kali",
        business: "4 kali",
        enterprise: "Prioritas",
      },
      {
        label: "Brand Guideline",
        professional: false,
        business: true,
        enterprise: true,
      },
      {
        label: "Social Media Identity",
        professional: "Basic",
        business: true,
        enterprise: true,
      },
      {
        label: "Company Profile / Packaging",
        professional: false,
        business: false,
        enterprise: true,
      },
    ],
    addOns: [
      {
        id: "branding-naming",
        title: "Brand Naming",
        description: "Riset dan pengembangan nama merek beserta alternatifnya.",
        priceLabel: "+Rp350k",
        priceValue: 350_000,
      },
      {
        id: "branding-packaging",
        title: "Additional Packaging Design",
        description: "Tambahan satu desain kemasan di luar cakupan paket.",
        priceLabel: "+Rp500k",
        priceValue: 500_000,
      },
      {
        id: "branding-social-template",
        title: "Additional Social Template",
        description: "Lima template tambahan untuk feed atau story media sosial.",
        priceLabel: "+Rp250k",
        priceValue: 250_000,
      },
      {
        id: "branding-trademark",
        title: "Trademark Preparation",
        description: "Persiapan dokumen visual untuk kebutuhan pengajuan merek.",
        priceLabel: "+Rp400k",
        priceValue: 400_000,
      },
    ],
  },

  "social-media": {
    key: "social-media",
    label: "Social Media Management",
    route: "/tanya-mahreen/paket/social-media",
    eyebrow: "Social Media Management",
    title: "Konfigurasi Paket Anda",
    description:
      "Kelola kehadiran media sosial secara konsisten melalui perencanaan konten, desain, copywriting, publikasi, dan evaluasi performa yang terarah.",
    tiers: [
      {
        id: "professional",
        tier: "Tier 01",
        name: "Better Package",
        price: 699_000,
        priceNote: "/ bulan",
        features: [
          "8 desain feed",
          "4 desain story",
          "Monthly content plan",
          "Caption writing",
          "Basic hashtag research",
          "1 revisi per konten",
          "Monthly performance report",
        ],
      },
      {
        id: "business",
        tier: "Tier 02",
        name: "Good Package",
        price: 999_000,
        priceNote: "/ bulan",
        features: [
          "12 desain feed/carousel",
          "8 desain story",
          "4 video Reels editing",
          "Content strategy",
          "Caption & CTA writing",
          "Hashtag & competitor research",
          "Content scheduling",
          "Monthly report",
          "1 sesi konsultasi",
        ],
        recommended: true,
      },
      {
        id: "enterprise",
        tier: "Tier 03",
        name: "Best Package",
        price: 1_999_000,
        priceNote: "/ bulan",
        features: [
          "20 desain feed/carousel",
          "12 desain story",
          "8 video Reels editing",
          "Full content strategy",
          "Copywriting & CTA",
          "Community management",
          "Scheduling & publishing",
          "Analytics & optimization",
          "Konsultasi dua mingguan",
          "Priority support",
        ],
      },
    ],
    comparisonRows: [
      {
        label: "Feed / Carousel per Bulan",
        professional: "8",
        business: "12",
        enterprise: "20",
      },
      {
        label: "Reels Editing",
        professional: false,
        business: "4 video",
        enterprise: "8 video",
      },
      {
        label: "Content Scheduling",
        professional: false,
        business: true,
        enterprise: true,
      },
      {
        label: "Community Management",
        professional: false,
        business: false,
        enterprise: true,
      },
      {
        label: "Strategy & Performance Review",
        professional: "Monthly",
        business: "Monthly + konsultasi",
        enterprise: "Biweekly",
      },
    ],
    addOns: [
      {
        id: "social-extra-reel",
        title: "Extra Reel Editing",
        description: "Tambahan satu video Reels dengan editing standar brand.",
        priceLabel: "+Rp250k",
        priceValue: 250_000,
      },
      {
        id: "social-photo-session",
        title: "Mini Photo Session",
        description: "Sesi foto produk atau brand berdurasi hingga dua jam.",
        priceLabel: "+Rp750k",
        priceValue: 750_000,
      },
      {
        id: "social-community",
        title: "Community Management",
        description: "Respons komentar dan pesan dasar selama jam operasional.",
        priceLabel: "+Rp1jt/bulan",
        priceValue: 1_000_000,
      },
      {
        id: "social-influencer",
        title: "Influencer Shortlist",
        description: "Riset dan daftar rekomendasi kreator sesuai target audiens.",
        priceLabel: "+Rp500k",
        priceValue: 500_000,
      },
    ],
  },

  "digital-marketing": {
    key: "digital-marketing",
    label: "Digital Marketing",
    route: "/tanya-mahreen/paket/digital-marketing",
    eyebrow: "Digital Marketing",
    title: "Konfigurasi Paket Anda",
    description:
      "Rancang strategi pemasaran digital berbasis data untuk meningkatkan jangkauan, kualitas prospek, konversi, dan pertumbuhan bisnis secara terukur.",
    tiers: [
      {
        id: "professional",
        tier: "Tier 01",
        name: "Better Package",
        price: 799_000,
        features: [
          "Digital presence audit",
          "Strategi 1 kanal utama",
          "Basic keyword research",
          "1 campaign setup",
          "Basic tracking setup",
          "Monthly performance report",
          "Rekomendasi optimasi",
        ],
      },
      {
        id: "business",
        tier: "Tier 02",
        name: "Good Package",
        price: 999_000,
        features: [
          "Multi-channel strategy",
          "SEO & SEM planning",
          "Hingga 2 campaign setup",
          "GA4 & Tag Manager setup",
          "Landing page review",
          "Weekly optimization",
          "Lead funnel recommendation",
          "Monthly strategy report",
        ],
        recommended: true,
      },
      {
        id: "enterprise",
        tier: "Tier 03",
        name: "Best Package",
        price: 1_999_000,
        features: [
          "Full-funnel marketing strategy",
          "Aktivasi hingga 3 kanal",
          "SEO content roadmap",
          "Advanced conversion tracking",
          "A/B testing plan",
          "Performance dashboard",
          "Weekly strategy meeting",
          "Continuous optimization",
          "Priority support",
        ],
      },
    ],
    comparisonRows: [
      {
        label: "Jumlah Kanal",
        professional: "1 kanal",
        business: "2 kanal",
        enterprise: "Hingga 3 kanal",
      },
      {
        label: "Campaign Setup",
        professional: "1 campaign",
        business: "2 campaign",
        enterprise: "Multi-campaign",
      },
      {
        label: "Conversion Tracking",
        professional: "Basic",
        business: true,
        enterprise: "Advanced",
      },
      {
        label: "A/B Testing",
        professional: false,
        business: false,
        enterprise: true,
      },
      {
        label: "Performance Dashboard",
        professional: false,
        business: false,
        enterprise: true,
      },
    ],
    addOns: [
      {
        id: "digital-landing-page",
        title: "Landing Page Optimization",
        description: "Audit dan rekomendasi peningkatan konversi landing page.",
        priceLabel: "+Rp750k",
        priceValue: 750_000,
      },
      {
        id: "digital-email",
        title: "Email Automation Setup",
        description: "Pengaturan alur email dasar untuk nurturing prospek.",
        priceLabel: "+Rp600k",
        priceValue: 600_000,
      },
      {
        id: "digital-dashboard",
        title: "Custom Analytics Dashboard",
        description: "Dashboard ringkas untuk KPI pemasaran utama.",
        priceLabel: "+Rp800k",
        priceValue: 800_000,
      },
      {
        id: "digital-competitor",
        title: "Competitor Deep Research",
        description: "Analisis kanal, pesan, dan positioning pesaing utama.",
        priceLabel: "+Rp500k",
        priceValue: 500_000,
      },
    ],
    taxNote: "*Belum termasuk PPN dan anggaran iklan",
  },

  advertising: {
    key: "advertising",
    label: "Advertising Campaign",
    route: "/tanya-mahreen/paket/advertising",
    eyebrow: "Advertising Campaign",
    title: "Konfigurasi Paket Anda",
    description:
      "Optimalkan kampanye berbayar melalui penentuan audiens, creative testing, tracking, monitoring, dan evaluasi performa yang disiplin.",
    tiers: [
      {
        id: "professional",
        tier: "Tier 01",
        name: "Better Package",
        price: 1_999_000,
        priceNote: "management fee",
        features: [
          "1 advertising platform",
          "1 campaign setup",
          "Audience targeting",
          "2 copy variants",
          "Basic pixel setup",
          "Biweekly monitoring",
          "Campaign report",
        ],
      },
      {
        id: "business",
        tier: "Tier 02",
        name: "Good Package",
        price: 2_499_000,
        priceNote: "management fee",
        features: [
          "Hingga 2 advertising platform",
          "Hingga 4 campaign setup",
          "Retargeting audience",
          "4 creative variations",
          "Conversion tracking",
          "Weekly optimization",
          "Weekly report",
          "1 strategy consultation",
        ],
        recommended: true,
      },
      {
        id: "enterprise",
        tier: "Tier 03",
        name: "Best Package",
        price: 2_999_000,
        priceNote: "management fee",
        features: [
          "Multi-platform advertising",
          "Hingga 8 campaign setup",
          "Full-funnel campaign",
          "Creative A/B testing",
          "Advanced tracking",
          "Daily monitoring",
          "Performance dashboard",
          "Weekly strategy meeting",
          "Priority optimization",
        ],
      },
    ],
    comparisonRows: [
      {
        label: "Advertising Platform",
        professional: "1",
        business: "2",
        enterprise: "Multi-platform",
      },
      {
        label: "Jumlah Campaign",
        professional: "1",
        business: "Hingga 4",
        enterprise: "Hingga 8",
      },
      {
        label: "Retargeting",
        professional: false,
        business: true,
        enterprise: true,
      },
      {
        label: "Creative A/B Testing",
        professional: false,
        business: "Basic",
        enterprise: "Advanced",
      },
      {
        label: "Monitoring",
        professional: "Biweekly",
        business: "Weekly",
        enterprise: "Daily",
      },
    ],
    addOns: [
      {
        id: "ads-extra-platform",
        title: "Additional Ad Platform",
        description: "Pengelolaan satu platform iklan tambahan.",
        priceLabel: "+Rp750k",
        priceValue: 750_000,
      },
      {
        id: "ads-creative-pack",
        title: "Creative Ads Pack",
        description: "Empat variasi visual dan copy tambahan untuk pengujian.",
        priceLabel: "+Rp500k",
        priceValue: 500_000,
      },
      {
        id: "ads-landing-page",
        title: "Campaign Landing Page",
        description: "Satu landing page sederhana untuk kebutuhan campaign.",
        priceLabel: "+Rp800k",
        priceValue: 800_000,
      },
      {
        id: "ads-rush",
        title: "Rush Campaign Setup",
        description: "Prioritas pengaturan campaign dengan waktu pengerjaan singkat.",
        priceLabel: "+Rp300k",
        priceValue: 300_000,
      },
    ],
    taxNote: "*Belum termasuk PPN dan anggaran media iklan",
  },

  "content-production": {
    key: "content-production",
    label: "Content Production",
    route: "/tanya-mahreen/paket/content-production",
    eyebrow: "Content Production",
    title: "Konfigurasi Paket Anda",
    description:
      "Produksi konten visual dan audiovisual yang konsisten dengan karakter brand, kebutuhan kanal, serta target komunikasi Anda.",
    tiers: [
      {
        id: "professional",
        tier: "Tier 01",
        name: "Better Package",
        price: 1_250_000,
        features: [
          "8 desain konten statis",
          "4 caption pendek",
          "1 simple Reel editing",
          "Adaptasi identitas brand",
          "Basic photo editing",
          "2 kali revisi",
          "File siap publikasi",
        ],
      },
      {
        id: "business",
        tier: "Tier 02",
        name: "Good Package",
        price: 1_499_000,
        features: [
          "12 desain feed/carousel",
          "4 video Reels editing",
          "Copywriting konten",
          "Content calendar",
          "Advanced photo editing",
          "Thumbnail & cover",
          "3 kali revisi",
          "File publikasi lengkap",
        ],
        recommended: true,
      },
      {
        id: "enterprise",
        tier: "Tier 03",
        name: "Best Package",
        price: 2_999_000,
        features: [
          "20 desain feed/carousel",
          "8 video Reels editing",
          "1 sesi foto/video produksi",
          "Scriptwriting",
          "Premium editing",
          "Content calendar",
          "Source files",
          "Priority production",
          "Support 14 hari",
        ],
      },
    ],
    comparisonRows: [
      {
        label: "Desain Statis",
        professional: "8",
        business: "12",
        enterprise: "20",
      },
      {
        label: "Video Reels",
        professional: "1",
        business: "4",
        enterprise: "8",
      },
      {
        label: "Copywriting",
        professional: "Basic",
        business: true,
        enterprise: true,
      },
      {
        label: "Production Session",
        professional: false,
        business: false,
        enterprise: true,
      },
      {
        label: "Source Files",
        professional: false,
        business: false,
        enterprise: true,
      },
    ],
    addOns: [
      {
        id: "content-extra-reel",
        title: "Extra Premium Reel",
        description: "Tambahan satu Reel dengan editing dan motion sederhana.",
        priceLabel: "+Rp300k",
        priceValue: 300_000,
      },
      {
        id: "content-product-photo",
        title: "Product Photography",
        description: "Sesi foto produk hingga sepuluh produk sederhana.",
        priceLabel: "+Rp1jt",
        priceValue: 1_000_000,
      },
      {
        id: "content-voice-over",
        title: "Professional Voice Over",
        description: "Voice over hingga 60 detik untuk satu konten video.",
        priceLabel: "+Rp350k",
        priceValue: 350_000,
      },
      {
        id: "content-motion",
        title: "Motion Graphic Add-on",
        description: "Tambahan motion graphic untuk satu konten utama.",
        priceLabel: "+Rp500k",
        priceValue: 500_000,
      },
    ],
  },

  consultation: {
    key: "consultation",
    label: "Business Consultation",
    route: "/tanya-mahreen/paket/consultation",
    eyebrow: "Business Consultation",
    title: "Konfigurasi Paket Anda",
    description:
      "Dapatkan arahan strategis yang terstruktur untuk menjawab persoalan bisnis, brand, pemasaran, dan transformasi digital Anda.",
    tiers: [
      {
        id: "professional",
        tier: "Tier 01",
        name: "Better Package",
        price: 749_000,
        features: [
          "1 sesi konsultasi 60 menit",
          "Initial business audit",
          "Pemetaan masalah utama",
          "Action notes",
          "Rekomendasi prioritas",
          "Follow-up 3 hari",
        ],
      },
      {
        id: "business",
        tier: "Tier 02",
        name: "Good Package",
        price: 1_499_000,
        features: [
          "2 sesi konsultasi @90 menit",
          "Detailed business audit",
          "Strategy roadmap",
          "Rekomendasi KPI",
          "Review dokumen pendukung",
          "Action plan terstruktur",
          "Follow-up 14 hari",
        ],
        recommended: true,
      },
      {
        id: "enterprise",
        tier: "Tier 03",
        name: "Best Package",
        price: 1_999_000,
        features: [
          "4 sesi konsultasi @90 menit",
          "Comprehensive business audit",
          "Customized strategy roadmap",
          "SOP & template rekomendasi",
          "Execution review",
          "WhatsApp support 30 hari",
          "Final strategic report",
          "Priority scheduling",
        ],
      },
    ],
    comparisonRows: [
      {
        label: "Sesi Konsultasi",
        professional: "1 × 60 menit",
        business: "2 × 90 menit",
        enterprise: "4 × 90 menit",
      },
      {
        label: "Business Audit",
        professional: "Initial",
        business: "Detailed",
        enterprise: "Comprehensive",
      },
      {
        label: "Strategy Roadmap",
        professional: false,
        business: true,
        enterprise: true,
      },
      {
        label: "SOP / Template",
        professional: false,
        business: false,
        enterprise: true,
      },
      {
        label: "Follow-up Support",
        professional: "3 hari",
        business: "14 hari",
        enterprise: "30 hari",
      },
    ],
    addOns: [
      {
        id: "consult-extra-session",
        title: "Additional Consultation Session",
        description: "Tambahan satu sesi konsultasi berdurasi hingga 90 menit.",
        priceLabel: "+Rp500k",
        priceValue: 500_000,
      },
      {
        id: "consult-workshop",
        title: "Team Strategy Workshop",
        description: "Workshop strategi untuk tim dengan durasi hingga tiga jam.",
        priceLabel: "+Rp1,5jt",
        priceValue: 1_500_000,
      },
      {
        id: "consult-sop",
        title: "Custom SOP Document",
        description: "Penyusunan satu dokumen SOP berdasarkan kebutuhan bisnis.",
        priceLabel: "+Rp750k",
        priceValue: 750_000,
      },
      {
        id: "consult-competitor",
        title: "Competitor Audit",
        description: "Analisis mendalam hingga tiga pesaing utama.",
        priceLabel: "+Rp600k",
        priceValue: 600_000,
      },
    ],
  },
};

export const getPackageServiceConfig = (key: PackageServiceKey) =>
  packageCatalog[key];
